@startuml SSD_CreateVaccineType
title SSD: UC1 - Create Vaccine Type

actor "Center Administrator" as Admin
participant ":System" as System

autonumber

Admin -> System: starts specifying a new vaccine type
activate System

System --> Admin: requests data (code, disease, recoveryPeriod) and presents list of technologies
deactivate System

Admin -> System: inputs data (code, disease, recoveryPeriod) and selects technology
activate System

System --> System: validate code uniqueness
alt invalid
    System --> Admin: informs duplicate code error
else valid
    System --> Admin: confirms successful creation
end

deactivate System
@enduml