@startuml SD_ScheduleVaccine_SNSUser
title SD: UC7 - Schedule a Vaccine Administration (SNS User)
skinparam maxMessageSize 150

actor "SNS User" as User
participant ": MainMenu" as UI
participant ": AppointmentController" as CTRL
participant ": HealthcareCenter" as HC
participant "appt: Appointment" as Appt

autonumber

activate User
User -> UI: starts scheduling a vaccine administration
activate UI

UI --> User: requests SNS User Number
deactivate UI

User -> UI: inputs SNS User Number
activate UI


UI -> CTRL: checkUserExists(snsNumber)
activate CTRL
CTRL -> HC: getSNSUser(snsNumber)
activate HC
HC --> CTRL: returns SNSUser* (or null)
deactivate HC
CTRL --> UI: returns boolean (true if exists)
deactivate CTRL

alt user not registered
    UI --> User: informs user not found error
else user registered

    UI -> CTRL: getVaccineCatalog()
    activate CTRL
    CTRL -> HC: getVaccineCatalog()
    activate HC
    HC --> CTRL: returns vector<VaccineType*>
    deactivate HC
    CTRL --> UI: returns list of types
    deactivate CTRL

    UI --> User: shows list of available Vaccine Types
    deactivate UI

    User -> UI: selects Vaccine Type and inputs Date/Time
    activate UI

    UI -> CTRL: validateDateTime(date, time)
    activate CTRL
    CTRL --> UI: returns validation result (true/false)
    deactivate CTRL

    alt date/time is in the past
        UI --> User: informs invalid date/time error
    else valid date/time
        UI --> User: displays appointment summary (Center, Date, Time, Type) and requests confirmation
        deactivate UI

        User -> UI: confirms the appointment
        activate UI

        UI -> CTRL: createAppointment(snsNumber, typeIndex, date, time)
        activate CTRL

        CTRL -> HC: getSNSUser(snsNumber)
        activate HC
        HC --> CTRL: returns user
        deactivate HC

        CTRL -> HC: getVaccineType(typeIndex)
        activate HC
        HC --> CTRL: returns type
        deactivate HC

        CTRL -> Appt ** : create(date, time, user, type)

        CTRL -> HC: addAppointment(appt)
        activate HC
        HC -> HC: masterSchedule.push_back(appt)
        HC --> CTRL: returns true
        deactivate HC

        CTRL --> UI: returns true
        deactivate CTRL

        UI --> User: confirms successful scheduling
    end
end

deactivate UI
deactivate User
@enduml