@startuml
'https://plantuml.com/use-case-diagram
title UC3 - List of Vaccines

actor "Center Administrator" as Admin
participant ":System" as System

autonumber

Admin -> System: Requests to get a list of the vaccine stock
activate System
System --> Admin: Shows the list (grouped by type and ordered by brand)
deactivate System

@enduml