@startuml
'https://plantuml.com/use-case-diagram
title UC4 - Register Employee

actor "Center Administrator" as Admin
participant ":System" as System

autonumber

Admin -> System: Requests to register a new employee
activate System
System --> Admin: Asks for the employee's information (Name, Phone, Email, CC, Role)
deactivate System
Admin -> System: Submits the employee's information
activate System
System --> Admin: Validates data and confirms employee registration
deactivate System

@enduml