@startuml UCD_Nurse
title Use Case Diagram - Nurse
left to right direction

actor "Nurse" as Nurse

rectangle "MedManager System" {
    usecase "UC9 - Consult SNS Users in the Waiting Room" as UC9
    usecase "UC10 - Record vaccine administration" as UC10
    usecase "UC12 - Consult Recovery Room" as UC12
}

Nurse --> UC9
Nurse --> UC10
Nurse --> UC12
@enduml