@startuml UCD_Nurse
title Use Case Diagram - Nurse
left to right direction

actor "Nurse" as Nurse


    usecase "UC9 - Consult SNS Users in the Waiting Room" as UC9
    usecase "UC10 - Record vaccine administration" as UC10

Nurse --> UC9
Nurse --> UC10
@enduml