@startuml SSD_RegisterVaccine
title SSD: UC2 - Register Physical Vaccine

actor "Center Administrator" as Admin
participant ":System" as System

autonumber
Admin -> System: starts vaccine registration
activate System

System --> Admin: shows list of VaccineTypes
deactivate System

Admin -> System: selects vaccine type
activate System

System --> Admin: requests data (name, brand, lotNumber, expirationDate, quantity)
deactivate System

Admin -> System: inputs data
activate System

System --> System: validate required fields

alt invalid
    System --> Admin: informs validation error
else valid
    System --> System: add vaccine to HealthcareCenter stock

    System --> Admin: confirms successful registration
end

deactivate System
@enduml