@startuml SSD_ListEmployees
title SSD: UC5 - List Employees by Role

actor "Center Administrator" as Admin
participant ":System" as System

autonumber

activate Admin
Admin -> System: requests a list of employees
activate System
System --> Admin: prompts to select a role (Nurse, Receptionist, Center Administrator)
deactivate System

Admin -> System: selects the desired role
activate System

alt invalid
    System --> Admin: informs that no employees are registered with that role
else valid
    System --> Admin: displays list of employees
end

deactivate System
deactivate Admin
@enduml