@startuml SSD_ListVaccines
title SSD: UC5 - List of Vaccines Stock


actor "Center Administrator" as Admin
participant ":System" as System

autonumber
activate Admin
Admin -> System: requests a list of all vaccines in the system
activate System

alt invalid
    System --> Admin: displays "Stock empty" message
else valid
     System --> Admin: displays vaccines grouped by type and sorted by brand
end

deactivate System
deactivate Admin
@enduml